### ISSUE TITLE
Error in ggbiplot when retx = FALSE in rpca

### ISSUE THREAD

**Issue by pcarbo** [Benli11/rSVD#2]
When I set `retx = FALSE` when running `rpca`, I get an error that is difficult to interpret, e.g.,

```
> data(iris)
> X   <- log(iris[1:4])
> out <- rpca(X,scale = FALSE,retx = FALSE)
> print(ggbiplot(out))
Error in `colnames<-`(`*tmp*`, value = c("a", "b")) :
  'names' attribute [2] must be the same length as the vector [0]
```

Perhaps you could report a more informative error in `ggbiplot` in this case?

Thanks,
Peter

**Comment by Benli11** [comment]
Hello Peter,

Thank you for bringing this up. I have added a proper error message for this issue, now.

Cheers,
Ben
